packages: []
overrides:
  vite: ^8.1.4
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
minimumReleaseAgeExclude:
  - "@hookform/resolvers@5.9.1"
  - nuqs@2.9.6
